name: Run Flow
description: 'Execute a named Cumulus flow'
inputs:
  org-name:
    description: 'Name of the scratch org or persistent org config to use'
    required: true
  flow-name:
    description: 'Name of the Cumulus flow to execute'
    required: true
  flow-task-options:
    description: 'Task options passed to the flow (ex -o __task__option value)'
    required: false
    default: ''
secrets:
  cumulusci-service-github:
    description: 'Value for CUMULUSCI_SERVICE_github'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Flow (with options)
      shell: bash
      env:
        CUMULUSCI_SERVICE_github: ${{ secrets.cumulusci-service-github }}
      run: |
        env && cci flow run ${{ inputs.flow-name }} --org ${{ inputs.org-name }} ${{ inputs.flow-task-options }} | tee cumulusci-flow.log
